[package]
name = "lala-bar"
version.workspace = true
edition.workspace = true
description = "a bar on layershell with iced-rs"
authors.workspace = true
license.workspace = true
keywords = ["sway", "waybar"]
readme.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.13.1", features = [
	"tokio",
	"debug",
	"image",
	"advanced",
	"svg",
	"markdown",
] }
iced_runtime = "0.13.2"
iced_layershell = "0.9.6"
tokio = { version = "1.41", features = ["full"] }
iced_futures = "0.13.2"
env_logger = "0.11.5"
tracing = "0.1.40"

futures-util.workspace = true
serde.workspace = true

zbus.workspace = true
tracing-subscriber = { version = "0.3.18", features = ["std", "env-filter"] }
anyhow = "1.0.93"
alsa = "0.9.1"

gio = "0.20.5"
regex = "1.11.1"
xdg = "2.5.2"
url.workspace = true
futures.workspace = true
iced_zbus_notification.workspace = true
chrono = "0.4.38"
async-trait.workspace = true
tracing-journald = "0.3.0"
